nome=input('Hello! Qual o seu nome?')
print('Prazer',nome,'seja bem vindx ao nosso grupo!')
dia=input('Qual o dia do seu nascimento?')
mes=input('Qual o mês do seu nascimento?')
ano=input('Qual o ano do seu nascimento?')
print('Você nasceu no dia',dia,'de',mes,'de',ano,'correto?')
